---
- name: "update apt"
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Add Node.js 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs

- name: "install dependencies."
  become: true
  apt:
    name: ["node.js" ,"npm", "python3"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present