---
- name: Copying files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: launch PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf artifact.tar.gz
    cd backend
    curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install
    pm2 stop default
    sudo npm run build
    sudo pm2 start npm --name backend -- start